### PR TITLE
Update page.tsx

### PR DESCRIPTION
**Pull request by MariolaH**

### CODE REVIEW

**Comment by joekr** [comment]
@MariolaH does this build locally?

**Comment by MariolaH** [comment]
> @MariolaH does this build locally?

Yes, it does

**Comment by joekr** [comment]
sorry looking into this again

**Comment by joekr** [comment]
So when I run it locally and go to `/about` I see the following error
image

and I see the same error in netlify build logs
image

**Comment by joekr** [comment]
AH! I think it is just missing the following dependency line in the `package.json`

`"aos": "^2.3.4"` (or whatever version should be used).

Once I add that it works.

**Comment by MariolaH** [comment]
Okay, awesome! Glad it was only that!

**Comment by joekr** [comment]
Do you mind adding that fix. My guess is the build will pass then we can merge this. 😁

**Comment by MariolaH** [comment]
I was having trouble pushing the code to the repo so I manually copy and
pasted the code into github.

**Pull request merged**
